//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CedServicios.RN.ar.gov.afip.personaServiceA5 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PersonaServiceA5SoapBinding", Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class PersonaServiceA5 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getPersonaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPersonaListOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPersona_v2OperationCompleted;
        
        private System.Threading.SendOrPostCallback dummyOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPersonaList_v2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PersonaServiceA5() {
            this.Url = global::CedServicios.RN.Properties.Settings.Default.CedServiciosRN_ar_gov_afip_personaServiceA5_PersonaServiceA5;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getPersonaCompletedEventHandler getPersonaCompleted;
        
        /// <remarks/>
        public event getPersonaListCompletedEventHandler getPersonaListCompleted;
        
        /// <remarks/>
        public event getPersona_v2CompletedEventHandler getPersona_v2Completed;
        
        /// <remarks/>
        public event dummyCompletedEventHandler dummyCompleted;
        
        /// <remarks/>
        public event getPersonaList_v2CompletedEventHandler getPersonaList_v2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://a5.soap.ws.server.puc.sr/", ResponseNamespace="http://a5.soap.ws.server.puc.sr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("personaReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public personaReturn getPersona([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string token, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string sign, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long cuitRepresentada, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long idPersona) {
            object[] results = this.Invoke("getPersona", new object[] {
                        token,
                        sign,
                        cuitRepresentada,
                        idPersona});
            return ((personaReturn)(results[0]));
        }
        
        /// <remarks/>
        public void getPersonaAsync(string token, string sign, long cuitRepresentada, long idPersona) {
            this.getPersonaAsync(token, sign, cuitRepresentada, idPersona, null);
        }
        
        /// <remarks/>
        public void getPersonaAsync(string token, string sign, long cuitRepresentada, long idPersona, object userState) {
            if ((this.getPersonaOperationCompleted == null)) {
                this.getPersonaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPersonaOperationCompleted);
            }
            this.InvokeAsync("getPersona", new object[] {
                        token,
                        sign,
                        cuitRepresentada,
                        idPersona}, this.getPersonaOperationCompleted, userState);
        }
        
        private void OngetPersonaOperationCompleted(object arg) {
            if ((this.getPersonaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPersonaCompleted(this, new getPersonaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://a5.soap.ws.server.puc.sr/", ResponseNamespace="http://a5.soap.ws.server.puc.sr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("personaListReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public personaListReturn getPersonaList([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string token, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string sign, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long cuitRepresentada, [System.Xml.Serialization.XmlElementAttribute("idPersona", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long[] idPersona) {
            object[] results = this.Invoke("getPersonaList", new object[] {
                        token,
                        sign,
                        cuitRepresentada,
                        idPersona});
            return ((personaListReturn)(results[0]));
        }
        
        /// <remarks/>
        public void getPersonaListAsync(string token, string sign, long cuitRepresentada, long[] idPersona) {
            this.getPersonaListAsync(token, sign, cuitRepresentada, idPersona, null);
        }
        
        /// <remarks/>
        public void getPersonaListAsync(string token, string sign, long cuitRepresentada, long[] idPersona, object userState) {
            if ((this.getPersonaListOperationCompleted == null)) {
                this.getPersonaListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPersonaListOperationCompleted);
            }
            this.InvokeAsync("getPersonaList", new object[] {
                        token,
                        sign,
                        cuitRepresentada,
                        idPersona}, this.getPersonaListOperationCompleted, userState);
        }
        
        private void OngetPersonaListOperationCompleted(object arg) {
            if ((this.getPersonaListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPersonaListCompleted(this, new getPersonaListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://a5.soap.ws.server.puc.sr/", ResponseNamespace="http://a5.soap.ws.server.puc.sr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("personaReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public personaReturn getPersona_v2([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string token, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string sign, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long cuitRepresentada, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long idPersona) {
            object[] results = this.Invoke("getPersona_v2", new object[] {
                        token,
                        sign,
                        cuitRepresentada,
                        idPersona});
            return ((personaReturn)(results[0]));
        }
        
        /// <remarks/>
        public void getPersona_v2Async(string token, string sign, long cuitRepresentada, long idPersona) {
            this.getPersona_v2Async(token, sign, cuitRepresentada, idPersona, null);
        }
        
        /// <remarks/>
        public void getPersona_v2Async(string token, string sign, long cuitRepresentada, long idPersona, object userState) {
            if ((this.getPersona_v2OperationCompleted == null)) {
                this.getPersona_v2OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPersona_v2OperationCompleted);
            }
            this.InvokeAsync("getPersona_v2", new object[] {
                        token,
                        sign,
                        cuitRepresentada,
                        idPersona}, this.getPersona_v2OperationCompleted, userState);
        }
        
        private void OngetPersona_v2OperationCompleted(object arg) {
            if ((this.getPersona_v2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPersona_v2Completed(this, new getPersona_v2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://a5.soap.ws.server.puc.sr/", ResponseNamespace="http://a5.soap.ws.server.puc.sr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dummyReturn dummy() {
            object[] results = this.Invoke("dummy", new object[0]);
            return ((dummyReturn)(results[0]));
        }
        
        /// <remarks/>
        public void dummyAsync() {
            this.dummyAsync(null);
        }
        
        /// <remarks/>
        public void dummyAsync(object userState) {
            if ((this.dummyOperationCompleted == null)) {
                this.dummyOperationCompleted = new System.Threading.SendOrPostCallback(this.OndummyOperationCompleted);
            }
            this.InvokeAsync("dummy", new object[0], this.dummyOperationCompleted, userState);
        }
        
        private void OndummyOperationCompleted(object arg) {
            if ((this.dummyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dummyCompleted(this, new dummyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://a5.soap.ws.server.puc.sr/", ResponseNamespace="http://a5.soap.ws.server.puc.sr/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("personaListReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public personaListReturn getPersonaList_v2([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string token, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string sign, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long cuitRepresentada, [System.Xml.Serialization.XmlElementAttribute("idPersona", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long[] idPersona) {
            object[] results = this.Invoke("getPersonaList_v2", new object[] {
                        token,
                        sign,
                        cuitRepresentada,
                        idPersona});
            return ((personaListReturn)(results[0]));
        }
        
        /// <remarks/>
        public void getPersonaList_v2Async(string token, string sign, long cuitRepresentada, long[] idPersona) {
            this.getPersonaList_v2Async(token, sign, cuitRepresentada, idPersona, null);
        }
        
        /// <remarks/>
        public void getPersonaList_v2Async(string token, string sign, long cuitRepresentada, long[] idPersona, object userState) {
            if ((this.getPersonaList_v2OperationCompleted == null)) {
                this.getPersonaList_v2OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPersonaList_v2OperationCompleted);
            }
            this.InvokeAsync("getPersonaList_v2", new object[] {
                        token,
                        sign,
                        cuitRepresentada,
                        idPersona}, this.getPersonaList_v2OperationCompleted, userState);
        }
        
        private void OngetPersonaList_v2OperationCompleted(object arg) {
            if ((this.getPersonaList_v2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPersonaList_v2Completed(this, new getPersonaList_v2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class personaReturn {
        
        private datosGenerales datosGeneralesField;
        
        private datosMonotributo datosMonotributoField;
        
        private datosRegimenGeneral datosRegimenGeneralField;
        
        private errorConstancia errorConstanciaField;
        
        private errorMonotributo errorMonotributoField;
        
        private errorRegimenGeneral errorRegimenGeneralField;
        
        private metadata metadataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public datosGenerales datosGenerales {
            get {
                return this.datosGeneralesField;
            }
            set {
                this.datosGeneralesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public datosMonotributo datosMonotributo {
            get {
                return this.datosMonotributoField;
            }
            set {
                this.datosMonotributoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public datosRegimenGeneral datosRegimenGeneral {
            get {
                return this.datosRegimenGeneralField;
            }
            set {
                this.datosRegimenGeneralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public errorConstancia errorConstancia {
            get {
                return this.errorConstanciaField;
            }
            set {
                this.errorConstanciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public errorMonotributo errorMonotributo {
            get {
                return this.errorMonotributoField;
            }
            set {
                this.errorMonotributoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public errorRegimenGeneral errorRegimenGeneral {
            get {
                return this.errorRegimenGeneralField;
            }
            set {
                this.errorRegimenGeneralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public metadata metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class datosGenerales {
        
        private string apellidoField;
        
        private caracterizacion[] caracterizacionField;
        
        private dependencia dependenciaField;
        
        private domicilio domicilioFiscalField;
        
        private string estadoClaveField;
        
        private System.DateTime fechaContratoSocialField;
        
        private bool fechaContratoSocialFieldSpecified;
        
        private System.DateTime fechaFallecimientoField;
        
        private bool fechaFallecimientoFieldSpecified;
        
        private long idPersonaField;
        
        private bool idPersonaFieldSpecified;
        
        private int mesCierreField;
        
        private bool mesCierreFieldSpecified;
        
        private string nombreField;
        
        private string razonSocialField;
        
        private string tipoClaveField;
        
        private string tipoPersonaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("caracterizacion", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public caracterizacion[] caracterizacion {
            get {
                return this.caracterizacionField;
            }
            set {
                this.caracterizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dependencia dependencia {
            get {
                return this.dependenciaField;
            }
            set {
                this.dependenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public domicilio domicilioFiscal {
            get {
                return this.domicilioFiscalField;
            }
            set {
                this.domicilioFiscalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estadoClave {
            get {
                return this.estadoClaveField;
            }
            set {
                this.estadoClaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaContratoSocial {
            get {
                return this.fechaContratoSocialField;
            }
            set {
                this.fechaContratoSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaContratoSocialSpecified {
            get {
                return this.fechaContratoSocialFieldSpecified;
            }
            set {
                this.fechaContratoSocialFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaFallecimiento {
            get {
                return this.fechaFallecimientoField;
            }
            set {
                this.fechaFallecimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFallecimientoSpecified {
            get {
                return this.fechaFallecimientoFieldSpecified;
            }
            set {
                this.fechaFallecimientoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaSpecified {
            get {
                return this.idPersonaFieldSpecified;
            }
            set {
                this.idPersonaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mesCierre {
            get {
                return this.mesCierreField;
            }
            set {
                this.mesCierreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mesCierreSpecified {
            get {
                return this.mesCierreFieldSpecified;
            }
            set {
                this.mesCierreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoClave {
            get {
                return this.tipoClaveField;
            }
            set {
                this.tipoClaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoPersona {
            get {
                return this.tipoPersonaField;
            }
            set {
                this.tipoPersonaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class caracterizacion {
        
        private string descripcionCaracterizacionField;
        
        private int idCaracterizacionField;
        
        private bool idCaracterizacionFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionCaracterizacion {
            get {
                return this.descripcionCaracterizacionField;
            }
            set {
                this.descripcionCaracterizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCaracterizacion {
            get {
                return this.idCaracterizacionField;
            }
            set {
                this.idCaracterizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCaracterizacionSpecified {
            get {
                return this.idCaracterizacionFieldSpecified;
            }
            set {
                this.idCaracterizacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified {
            get {
                return this.periodoFieldSpecified;
            }
            set {
                this.periodoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class dummyReturn {
        
        private string appserverField;
        
        private string authserverField;
        
        private string dbserverField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appserver {
            get {
                return this.appserverField;
            }
            set {
                this.appserverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authserver {
            get {
                return this.authserverField;
            }
            set {
                this.authserverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dbserver {
            get {
                return this.dbserverField;
            }
            set {
                this.dbserverField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class persona {
        
        private datosGenerales datosGeneralesField;
        
        private datosMonotributo datosMonotributoField;
        
        private datosRegimenGeneral datosRegimenGeneralField;
        
        private errorConstancia errorConstanciaField;
        
        private errorMonotributo errorMonotributoField;
        
        private errorRegimenGeneral errorRegimenGeneralField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public datosGenerales datosGenerales {
            get {
                return this.datosGeneralesField;
            }
            set {
                this.datosGeneralesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public datosMonotributo datosMonotributo {
            get {
                return this.datosMonotributoField;
            }
            set {
                this.datosMonotributoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public datosRegimenGeneral datosRegimenGeneral {
            get {
                return this.datosRegimenGeneralField;
            }
            set {
                this.datosRegimenGeneralField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public errorConstancia errorConstancia {
            get {
                return this.errorConstanciaField;
            }
            set {
                this.errorConstanciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public errorMonotributo errorMonotributo {
            get {
                return this.errorMonotributoField;
            }
            set {
                this.errorMonotributoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public errorRegimenGeneral errorRegimenGeneral {
            get {
                return this.errorRegimenGeneralField;
            }
            set {
                this.errorRegimenGeneralField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class datosMonotributo {
        
        private actividad[] actividadField;
        
        private actividad actividadMonotributistaField;
        
        private categoria categoriaMonotributoField;
        
        private relacion[] componenteDeSociedadField;
        
        private impuesto[] impuestoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("actividad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public actividad[] actividad {
            get {
                return this.actividadField;
            }
            set {
                this.actividadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public actividad actividadMonotributista {
            get {
                return this.actividadMonotributistaField;
            }
            set {
                this.actividadMonotributistaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public categoria categoriaMonotributo {
            get {
                return this.categoriaMonotributoField;
            }
            set {
                this.categoriaMonotributoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("componenteDeSociedad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public relacion[] componenteDeSociedad {
            get {
                return this.componenteDeSociedadField;
            }
            set {
                this.componenteDeSociedadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("impuesto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public impuesto[] impuesto {
            get {
                return this.impuestoField;
            }
            set {
                this.impuestoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class actividad {
        
        private string descripcionActividadField;
        
        private long idActividadField;
        
        private bool idActividadFieldSpecified;
        
        private int nomencladorField;
        
        private bool nomencladorFieldSpecified;
        
        private int ordenField;
        
        private bool ordenFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionActividad {
            get {
                return this.descripcionActividadField;
            }
            set {
                this.descripcionActividadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idActividad {
            get {
                return this.idActividadField;
            }
            set {
                this.idActividadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idActividadSpecified {
            get {
                return this.idActividadFieldSpecified;
            }
            set {
                this.idActividadFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int nomenclador {
            get {
                return this.nomencladorField;
            }
            set {
                this.nomencladorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nomencladorSpecified {
            get {
                return this.nomencladorFieldSpecified;
            }
            set {
                this.nomencladorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ordenSpecified {
            get {
                return this.ordenFieldSpecified;
            }
            set {
                this.ordenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified {
            get {
                return this.periodoFieldSpecified;
            }
            set {
                this.periodoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class categoria {
        
        private string descripcionCategoriaField;
        
        private int idCategoriaField;
        
        private bool idCategoriaFieldSpecified;
        
        private int idImpuestoField;
        
        private bool idImpuestoFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionCategoria {
            get {
                return this.descripcionCategoriaField;
            }
            set {
                this.descripcionCategoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                this.idCategoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCategoriaSpecified {
            get {
                return this.idCategoriaFieldSpecified;
            }
            set {
                this.idCategoriaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idImpuesto {
            get {
                return this.idImpuestoField;
            }
            set {
                this.idImpuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImpuestoSpecified {
            get {
                return this.idImpuestoFieldSpecified;
            }
            set {
                this.idImpuestoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified {
            get {
                return this.periodoFieldSpecified;
            }
            set {
                this.periodoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class relacion {
        
        private string apellidoPersonaAsociadaField;
        
        private System.DateTime ffRelacionField;
        
        private bool ffRelacionFieldSpecified;
        
        private System.DateTime ffVencimientoField;
        
        private bool ffVencimientoFieldSpecified;
        
        private long idPersonaAsociadaField;
        
        private bool idPersonaAsociadaFieldSpecified;
        
        private string nombrePersonaAsociadaField;
        
        private string razonSocialPersonaAsociadaField;
        
        private string tipoComponenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoPersonaAsociada {
            get {
                return this.apellidoPersonaAsociadaField;
            }
            set {
                this.apellidoPersonaAsociadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime ffRelacion {
            get {
                return this.ffRelacionField;
            }
            set {
                this.ffRelacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ffRelacionSpecified {
            get {
                return this.ffRelacionFieldSpecified;
            }
            set {
                this.ffRelacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime ffVencimiento {
            get {
                return this.ffVencimientoField;
            }
            set {
                this.ffVencimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ffVencimientoSpecified {
            get {
                return this.ffVencimientoFieldSpecified;
            }
            set {
                this.ffVencimientoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idPersonaAsociada {
            get {
                return this.idPersonaAsociadaField;
            }
            set {
                this.idPersonaAsociadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaAsociadaSpecified {
            get {
                return this.idPersonaAsociadaFieldSpecified;
            }
            set {
                this.idPersonaAsociadaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombrePersonaAsociada {
            get {
                return this.nombrePersonaAsociadaField;
            }
            set {
                this.nombrePersonaAsociadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string razonSocialPersonaAsociada {
            get {
                return this.razonSocialPersonaAsociadaField;
            }
            set {
                this.razonSocialPersonaAsociadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoComponente {
            get {
                return this.tipoComponenteField;
            }
            set {
                this.tipoComponenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class impuesto {
        
        private string descripcionImpuestoField;
        
        private int idImpuestoField;
        
        private bool idImpuestoFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionImpuesto {
            get {
                return this.descripcionImpuestoField;
            }
            set {
                this.descripcionImpuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idImpuesto {
            get {
                return this.idImpuestoField;
            }
            set {
                this.idImpuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImpuestoSpecified {
            get {
                return this.idImpuestoFieldSpecified;
            }
            set {
                this.idImpuestoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified {
            get {
                return this.periodoFieldSpecified;
            }
            set {
                this.periodoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class datosRegimenGeneral {
        
        private actividad[] actividadField;
        
        private categoria categoriaAutonomoField;
        
        private impuesto[] impuestoField;
        
        private regimen[] regimenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("actividad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public actividad[] actividad {
            get {
                return this.actividadField;
            }
            set {
                this.actividadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public categoria categoriaAutonomo {
            get {
                return this.categoriaAutonomoField;
            }
            set {
                this.categoriaAutonomoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("impuesto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public impuesto[] impuesto {
            get {
                return this.impuestoField;
            }
            set {
                this.impuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("regimen", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public regimen[] regimen {
            get {
                return this.regimenField;
            }
            set {
                this.regimenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class regimen {
        
        private string descripcionRegimenField;
        
        private int idImpuestoField;
        
        private bool idImpuestoFieldSpecified;
        
        private int idRegimenField;
        
        private bool idRegimenFieldSpecified;
        
        private int periodoField;
        
        private bool periodoFieldSpecified;
        
        private string tipoRegimenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionRegimen {
            get {
                return this.descripcionRegimenField;
            }
            set {
                this.descripcionRegimenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idImpuesto {
            get {
                return this.idImpuestoField;
            }
            set {
                this.idImpuestoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idImpuestoSpecified {
            get {
                return this.idImpuestoFieldSpecified;
            }
            set {
                this.idImpuestoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idRegimen {
            get {
                return this.idRegimenField;
            }
            set {
                this.idRegimenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idRegimenSpecified {
            get {
                return this.idRegimenFieldSpecified;
            }
            set {
                this.idRegimenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool periodoSpecified {
            get {
                return this.periodoFieldSpecified;
            }
            set {
                this.periodoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoRegimen {
            get {
                return this.tipoRegimenField;
            }
            set {
                this.tipoRegimenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class errorConstancia {
        
        private string apellidoField;
        
        private string[] errorField;
        
        private long idPersonaField;
        
        private bool idPersonaFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaSpecified {
            get {
                return this.idPersonaFieldSpecified;
            }
            set {
                this.idPersonaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class errorMonotributo {
        
        private string[] errorField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class errorRegimenGeneral {
        
        private string[] errorField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class personaListReturn {
        
        private metadata metadataField;
        
        private persona[] personaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public metadata metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("persona", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public persona[] persona {
            get {
                return this.personaField;
            }
            set {
                this.personaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class metadata {
        
        private System.DateTime fechaHoraField;
        
        private bool fechaHoraFieldSpecified;
        
        private string servidorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaHoraSpecified {
            get {
                return this.fechaHoraFieldSpecified;
            }
            set {
                this.fechaHoraFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string servidor {
            get {
                return this.servidorField;
            }
            set {
                this.servidorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class domicilio {
        
        private string codPostalField;
        
        private string datoAdicionalField;
        
        private string descripcionProvinciaField;
        
        private string direccionField;
        
        private int idProvinciaField;
        
        private bool idProvinciaFieldSpecified;
        
        private string localidadField;
        
        private string tipoDatoAdicionalField;
        
        private string tipoDomicilioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPostal {
            get {
                return this.codPostalField;
            }
            set {
                this.codPostalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string datoAdicional {
            get {
                return this.datoAdicionalField;
            }
            set {
                this.datoAdicionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionProvincia {
            get {
                return this.descripcionProvinciaField;
            }
            set {
                this.descripcionProvinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProvincia {
            get {
                return this.idProvinciaField;
            }
            set {
                this.idProvinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProvinciaSpecified {
            get {
                return this.idProvinciaFieldSpecified;
            }
            set {
                this.idProvinciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDatoAdicional {
            get {
                return this.tipoDatoAdicionalField;
            }
            set {
                this.tipoDatoAdicionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDomicilio {
            get {
                return this.tipoDomicilioField;
            }
            set {
                this.tipoDomicilioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://a5.soap.ws.server.puc.sr/")]
    public partial class dependencia {
        
        private string codPostalField;
        
        private string descripcionDependenciaField;
        
        private string descripcionProvinciaField;
        
        private string direccionField;
        
        private int idDependenciaField;
        
        private bool idDependenciaFieldSpecified;
        
        private int idProvinciaField;
        
        private bool idProvinciaFieldSpecified;
        
        private string localidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codPostal {
            get {
                return this.codPostalField;
            }
            set {
                this.codPostalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionDependencia {
            get {
                return this.descripcionDependenciaField;
            }
            set {
                this.descripcionDependenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcionProvincia {
            get {
                return this.descripcionProvinciaField;
            }
            set {
                this.descripcionProvinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDependencia {
            get {
                return this.idDependenciaField;
            }
            set {
                this.idDependenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idDependenciaSpecified {
            get {
                return this.idDependenciaFieldSpecified;
            }
            set {
                this.idDependenciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProvincia {
            get {
                return this.idProvinciaField;
            }
            set {
                this.idProvinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProvinciaSpecified {
            get {
                return this.idProvinciaFieldSpecified;
            }
            set {
                this.idProvinciaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string localidad {
            get {
                return this.localidadField;
            }
            set {
                this.localidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getPersonaCompletedEventHandler(object sender, getPersonaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPersonaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPersonaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public personaReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((personaReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getPersonaListCompletedEventHandler(object sender, getPersonaListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPersonaListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPersonaListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public personaListReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((personaListReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getPersona_v2CompletedEventHandler(object sender, getPersona_v2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPersona_v2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPersona_v2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public personaReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((personaReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void dummyCompletedEventHandler(object sender, dummyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dummyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dummyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public dummyReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((dummyReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getPersonaList_v2CompletedEventHandler(object sender, getPersonaList_v2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPersonaList_v2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPersonaList_v2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public personaListReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((personaListReturn)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591