drop table dbo.Articulo
drop table dbo.PuntoVta
drop table dbo.MetodoGeneracionNumeracionLote
drop table dbo.TipoPuntoVta
drop table dbo.UN
drop table dbo.Usuario
drop table dbo.Cliente
drop table dbo.Configuracion
drop table dbo.LogDetalle
drop table dbo.Log
drop table dbo.Permiso
drop table dbo.TipoPermiso
drop table dbo.Cuit
drop table dbo.Medio
