insert EsquemaContable values (30, 'Compra', 'T', 'Pas-Db-Proveed', -1)
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'A', 'Gs-Compras', -Signo from EsquemaContable where IdNaturalezaComprobante like 'Compra%' and Concepto='T' and IdTipoComprobante=30
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'D', 'Gs-Compras', Signo from EsquemaContable where IdNaturalezaComprobante like 'Compra%' and Concepto='T' and IdTipoComprobante=30
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-21', 'Act-Cr-I-Iva21', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=30
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-10.5', 'Act-Cr-I-Iva10.5', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=30
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-27', 'Act-Cr-I-Iva27', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=30
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-0', 'Act-Cr-I-Iva0', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=30
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-3', 'Act-Cr-I-Otros', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=30
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-5', 'Act-Cr-I-IngBrut', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=30
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-2', 'Act-Cr-I-ImpInt', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=30
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-6', 'Act-Cr-I-ImpMun', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=30
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-4', 'Act-Cr-I-PercepINac', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=30
insert EsquemaContable values (67, 'Compra', 'T', 'Pas-Db-Proveed', -1)
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'A', 'Gs-Compras', -Signo from EsquemaContable where IdNaturalezaComprobante like 'Compra%' and Concepto='T' and IdTipoComprobante=67
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'D', 'Gs-Compras', Signo from EsquemaContable where IdNaturalezaComprobante like 'Compra%' and Concepto='T' and IdTipoComprobante=67
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-21', 'Act-Cr-I-Iva21', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=67
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-10.5', 'Act-Cr-I-Iva10.5', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=67
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-27', 'Act-Cr-I-Iva27', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=67
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-0', 'Act-Cr-I-Iva0', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=67
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-3', 'Act-Cr-I-Otros', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=67
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-5', 'Act-Cr-I-IngBrut', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=67
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-2', 'Act-Cr-I-ImpInt', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=67
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-6', 'Act-Cr-I-ImpMun', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=67
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-4', 'Act-Cr-I-PercepINac', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=67
insert EsquemaContable values (85, 'Compra', 'T', 'Pas-Db-Proveed', -1)
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'A', 'Gs-Compras', -Signo from EsquemaContable where IdNaturalezaComprobante like 'Compra%' and Concepto='T' and IdTipoComprobante=85
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'D', 'Gs-Compras', Signo from EsquemaContable where IdNaturalezaComprobante like 'Compra%' and Concepto='T' and IdTipoComprobante=85
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-21', 'Act-Cr-I-Iva21', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=85
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-10.5', 'Act-Cr-I-Iva10.5', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=85
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-27', 'Act-Cr-I-Iva27', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=85
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-0', 'Act-Cr-I-Iva0', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=85
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-3', 'Act-Cr-I-Otros', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=85
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-5', 'Act-Cr-I-IngBrut', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=85
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-2', 'Act-Cr-I-ImpInt', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=85
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-6', 'Act-Cr-I-ImpMun', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=85
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-4', 'Act-Cr-I-PercepINac', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=85
insert EsquemaContable values (86, 'Compra', 'T', 'Pas-Db-Proveed', -1)
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'A', 'Gs-Compras', -Signo from EsquemaContable where IdNaturalezaComprobante like 'Compra%' and Concepto='T' and IdTipoComprobante=86
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'D', 'Gs-Compras', Signo from EsquemaContable where IdNaturalezaComprobante like 'Compra%' and Concepto='T' and IdTipoComprobante=86
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-21', 'Act-Cr-I-Iva21', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=86
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-10.5', 'Act-Cr-I-Iva10.5', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=86
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-27', 'Act-Cr-I-Iva27', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=86
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-0', 'Act-Cr-I-Iva0', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=86
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-3', 'Act-Cr-I-Otros', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=86
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-5', 'Act-Cr-I-IngBrut', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=86
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-2', 'Act-Cr-I-ImpInt', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=86
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-6', 'Act-Cr-I-ImpMun', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=86
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-4', 'Act-Cr-I-PercepINac', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=86
insert EsquemaContable values (70, 'Compra', 'T', 'Pas-Db-Proveed', -1)
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'A', 'Gs-Compras', -Signo from EsquemaContable where IdNaturalezaComprobante like 'Compra%' and Concepto='T' and IdTipoComprobante=70
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'D', 'Gs-Compras', Signo from EsquemaContable where IdNaturalezaComprobante like 'Compra%' and Concepto='T' and IdTipoComprobante=70
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-21', 'Act-Cr-I-Iva21', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=70
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-10.5', 'Act-Cr-I-Iva10.5', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=70
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-27', 'Act-Cr-I-Iva27', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=70
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-0', 'Act-Cr-I-Iva0', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=70
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-3', 'Act-Cr-I-Otros', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=70
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-5', 'Act-Cr-I-IngBrut', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=70
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-2', 'Act-Cr-I-ImpInt', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=70
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-6', 'Act-Cr-I-ImpMun', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=70
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-4', 'Act-Cr-I-PercepINac', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=70
insert EsquemaContable values (83, 'Compra', 'T', 'Pas-Db-Proveed', -1)
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'A', 'Gs-Compras', -Signo from EsquemaContable where IdNaturalezaComprobante like 'Compra%' and Concepto='T' and IdTipoComprobante=83
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'D', 'Gs-Compras', Signo from EsquemaContable where IdNaturalezaComprobante like 'Compra%' and Concepto='T' and IdTipoComprobante=83
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-21', 'Act-Cr-I-Iva21', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=83
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-10.5', 'Act-Cr-I-Iva10.5', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=83
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-27', 'Act-Cr-I-Iva27', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=83
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-0', 'Act-Cr-I-Iva0', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=83
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-3', 'Act-Cr-I-Otros', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=83
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-5', 'Act-Cr-I-IngBrut', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=83
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-2', 'Act-Cr-I-ImpInt', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=83
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-6', 'Act-Cr-I-ImpMun', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=83
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-4', 'Act-Cr-I-PercepINac', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=83
insert EsquemaContable values (81, 'Compra', 'T', 'Pas-Db-Proveed', -1)
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'A', 'Gs-Compras', -Signo from EsquemaContable where IdNaturalezaComprobante like 'Compra%' and Concepto='T' and IdTipoComprobante=81
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'D', 'Gs-Compras', Signo from EsquemaContable where IdNaturalezaComprobante like 'Compra%' and Concepto='T' and IdTipoComprobante=81
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-21', 'Act-Cr-I-Iva21', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=81
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-10.5', 'Act-Cr-I-Iva10.5', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=81
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-27', 'Act-Cr-I-Iva27', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=81
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-0', 'Act-Cr-I-Iva0', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=81
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-3', 'Act-Cr-I-Otros', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=81
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-5', 'Act-Cr-I-IngBrut', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=81
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-2', 'Act-Cr-I-ImpInt', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=81
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-6', 'Act-Cr-I-ImpMun', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=81
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-4', 'Act-Cr-I-PercepINac', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=81
insert EsquemaContable values (82, 'Compra', 'T', 'Pas-Db-Proveed', -1)
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'A', 'Gs-Compras', -Signo from EsquemaContable where IdNaturalezaComprobante like 'Compra%' and Concepto='T' and IdTipoComprobante=82
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'D', 'Gs-Compras', Signo from EsquemaContable where IdNaturalezaComprobante like 'Compra%' and Concepto='T' and IdTipoComprobante=82
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-21', 'Act-Cr-I-Iva21', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=82
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-10.5', 'Act-Cr-I-Iva10.5', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=82
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-27', 'Act-Cr-I-Iva27', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=82
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-1-0', 'Act-Cr-I-Iva0', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=82
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-3', 'Act-Cr-I-Otros', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=82
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-5', 'Act-Cr-I-IngBrut', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=82
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-2', 'Act-Cr-I-ImpInt', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=82
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-6', 'Act-Cr-I-ImpMun', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=82
insert EsquemaContable select IdTipoComprobante, IdNaturalezaComprobante, 'I-4', 'Act-Cr-I-PercepINac', -Signo from EsquemaContable where IdNaturalezaComprobante = 'Compra' and Concepto='T' and IdTipoComprobante=82
