INSERT INTO PuntoVta
           (Cuit
           ,NroPuntoVta
           ,IdUN
           ,IdTipoPuntoVta
           ,UsaSetPropioDeDatosCuit
           ,Calle
           ,Nro
           ,Piso
           ,Depto
           ,Sector
           ,Torre
           ,Manzana
           ,Localidad
           ,IdProvincia
           ,DescrProvincia
           ,CodPost
           ,NombreContacto
           ,EmailContacto
           ,TelefonoContacto
           ,IdCondIVA
           ,DescrCondIVA
           ,NroIngBrutos
           ,IdCondIngBrutos
           ,DescrCondIngBrutos
           ,GLN
           ,FechaInicioActividades
           ,CodigoInterno
           ,IdMetodoGeneracionNumeracionLote
           ,UltNroLote
           ,IdWF
           ,Estado)
     VALUES
           ('30710015062'
           ,1
           ,'BUE'
           ,'Comun'
           ,0
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,0
           ,''
           ,''
           ,0
           ,''
           ,0
           ,'19000101'
           ,''
           ,'Ninguno'
           ,0
           ,0
           ,'Vigente')
GO
INSERT INTO PuntoVta
           (Cuit
           ,NroPuntoVta
           ,IdUN
           ,IdTipoPuntoVta
           ,UsaSetPropioDeDatosCuit
           ,Calle
           ,Nro
           ,Piso
           ,Depto
           ,Sector
           ,Torre
           ,Manzana
           ,Localidad
           ,IdProvincia
           ,DescrProvincia
           ,CodPost
           ,NombreContacto
           ,EmailContacto
           ,TelefonoContacto
           ,IdCondIVA
           ,DescrCondIVA
           ,NroIngBrutos
           ,IdCondIngBrutos
           ,DescrCondIngBrutos
           ,GLN
           ,FechaInicioActividades
           ,CodigoInterno
           ,IdMetodoGeneracionNumeracionLote
           ,UltNroLote
           ,IdWF
           ,Estado)
     VALUES
           ('30710015062'
           ,2
           ,'BUE'
           ,'Comun'
           ,0
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,0
           ,''
           ,''
           ,0
           ,''
           ,0
           ,'19000101'
           ,''
           ,'Ninguno'
           ,0
           ,0
           ,'Vigente')
GO
INSERT INTO PuntoVta
           (Cuit
           ,NroPuntoVta
           ,IdUN
           ,IdTipoPuntoVta
           ,UsaSetPropioDeDatosCuit
           ,Calle
           ,Nro
           ,Piso
           ,Depto
           ,Sector
           ,Torre
           ,Manzana
           ,Localidad
           ,IdProvincia
           ,DescrProvincia
           ,CodPost
           ,NombreContacto
           ,EmailContacto
           ,TelefonoContacto
           ,IdCondIVA
           ,DescrCondIVA
           ,NroIngBrutos
           ,IdCondIngBrutos
           ,DescrCondIngBrutos
           ,GLN
           ,FechaInicioActividades
           ,CodigoInterno
           ,IdMetodoGeneracionNumeracionLote
           ,UltNroLote
           ,IdWF
           ,Estado)
     VALUES
           ('30710015062'
           ,3
           ,'MDQ'
           ,'Comun'
           ,0
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,''
           ,0
           ,''
           ,''
           ,0
           ,''
           ,0
           ,'19000101'
           ,''
           ,'Ninguno'
           ,0
           ,0
           ,'Vigente')
GO
